package edu.graduate.bean;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_article.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_article.picture
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_article.date
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_article.desc
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_article.id
     *
     * @return the value of graduate_article.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_article.id
     *
     * @param id the value for graduate_article.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_article.picture
     *
     * @return the value of graduate_article.picture
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_article.picture
     *
     * @param picture the value for graduate_article.picture
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_article.date
     *
     * @return the value of graduate_article.date
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_article.date
     *
     * @param date the value for graduate_article.date
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_article.desc
     *
     * @return the value of graduate_article.desc
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_article.desc
     *
     * @param desc the value for graduate_article.desc
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}