package edu.graduate.bean;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_comment.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_comment.username
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_comment.score
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_comment.article_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_comment.desc
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_comment.id
     *
     * @return the value of graduate_comment.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_comment.id
     *
     * @param id the value for graduate_comment.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_comment.username
     *
     * @return the value of graduate_comment.username
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_comment.username
     *
     * @param username the value for graduate_comment.username
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_comment.score
     *
     * @return the value of graduate_comment.score
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_comment.score
     *
     * @param score the value for graduate_comment.score
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_comment.article_id
     *
     * @return the value of graduate_comment.article_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_comment.article_id
     *
     * @param articleId the value for graduate_comment.article_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_comment.desc
     *
     * @return the value of graduate_comment.desc
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_comment.desc
     *
     * @param desc the value for graduate_comment.desc
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}