package edu.graduate.bean;

public class Fruit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.id
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.name
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.picture
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.preganInfo_id
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    private Long preganinfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.desc
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.id
     *
     * @return the value of graduate_fruit.id
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.id
     *
     * @param id the value for graduate_fruit.id
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.name
     *
     * @return the value of graduate_fruit.name
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.name
     *
     * @param name the value for graduate_fruit.name
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.picture
     *
     * @return the value of graduate_fruit.picture
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.picture
     *
     * @param picture the value for graduate_fruit.picture
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.preganInfo_id
     *
     * @return the value of graduate_fruit.preganInfo_id
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public Long getPreganinfoId() {
        return preganinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.preganInfo_id
     *
     * @param preganinfoId the value for graduate_fruit.preganInfo_id
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public void setPreganinfoId(Long preganinfoId) {
        this.preganinfoId = preganinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.desc
     *
     * @return the value of graduate_fruit.desc
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.desc
     *
     * @param desc the value for graduate_fruit.desc
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}