package edu.graduate.bean;

public class Fruit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.id
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.name
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.picture
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.brief
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    private String brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.description
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.pregnantEat
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    private String pregnanteat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.momEat
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    private String momeat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_fruit.babyEat
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    private String babyeat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.id
     *
     * @return the value of graduate_fruit.id
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.id
     *
     * @param id the value for graduate_fruit.id
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.name
     *
     * @return the value of graduate_fruit.name
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.name
     *
     * @param name the value for graduate_fruit.name
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.picture
     *
     * @return the value of graduate_fruit.picture
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.picture
     *
     * @param picture the value for graduate_fruit.picture
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.brief
     *
     * @return the value of graduate_fruit.brief
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.brief
     *
     * @param brief the value for graduate_fruit.brief
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.description
     *
     * @return the value of graduate_fruit.description
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.description
     *
     * @param description the value for graduate_fruit.description
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.pregnantEat
     *
     * @return the value of graduate_fruit.pregnantEat
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public String getPregnanteat() {
        return pregnanteat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.pregnantEat
     *
     * @param pregnanteat the value for graduate_fruit.pregnantEat
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public void setPregnanteat(String pregnanteat) {
        this.pregnanteat = pregnanteat == null ? null : pregnanteat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.momEat
     *
     * @return the value of graduate_fruit.momEat
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public String getMomeat() {
        return momeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.momEat
     *
     * @param momeat the value for graduate_fruit.momEat
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public void setMomeat(String momeat) {
        this.momeat = momeat == null ? null : momeat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_fruit.babyEat
     *
     * @return the value of graduate_fruit.babyEat
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public String getBabyeat() {
        return babyeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_fruit.babyEat
     *
     * @param babyeat the value for graduate_fruit.babyEat
     *
     * @mbg.generated Fri May 17 21:35:09 CST 2019
     */
    public void setBabyeat(String babyeat) {
        this.babyeat = babyeat == null ? null : babyeat.trim();
    }
}