package edu.graduate.bean;

public class ImgIndexButtom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_imgindex_buttom.id
     *
     * @mbg.generated Tue May 07 20:37:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_imgindex_buttom.imgPath
     *
     * @mbg.generated Tue May 07 20:37:04 CST 2019
     */
    private String imgpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_imgindex_buttom.content
     *
     * @mbg.generated Tue May 07 20:37:04 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_imgindex_buttom.id
     *
     * @return the value of graduate_imgindex_buttom.id
     *
     * @mbg.generated Tue May 07 20:37:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_imgindex_buttom.id
     *
     * @param id the value for graduate_imgindex_buttom.id
     *
     * @mbg.generated Tue May 07 20:37:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_imgindex_buttom.imgPath
     *
     * @return the value of graduate_imgindex_buttom.imgPath
     *
     * @mbg.generated Tue May 07 20:37:04 CST 2019
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_imgindex_buttom.imgPath
     *
     * @param imgpath the value for graduate_imgindex_buttom.imgPath
     *
     * @mbg.generated Tue May 07 20:37:04 CST 2019
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_imgindex_buttom.content
     *
     * @return the value of graduate_imgindex_buttom.content
     *
     * @mbg.generated Tue May 07 20:37:04 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_imgindex_buttom.content
     *
     * @param content the value for graduate_imgindex_buttom.content
     *
     * @mbg.generated Tue May 07 20:37:04 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}