package edu.graduate.bean;

public class ImgPregnant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_imgpregnant.id
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_imgpregnant.imgPath
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    private String imgpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_imgpregnant.id
     *
     * @return the value of graduate_imgpregnant.id
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_imgpregnant.id
     *
     * @param id the value for graduate_imgpregnant.id
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_imgpregnant.imgPath
     *
     * @return the value of graduate_imgpregnant.imgPath
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_imgpregnant.imgPath
     *
     * @param imgpath the value for graduate_imgpregnant.imgPath
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }
}