package edu.graduate.bean;

public class Kind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_kind.id
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_kind.kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    private String kind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_kind.id
     *
     * @return the value of graduate_kind.id
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_kind.id
     *
     * @param id the value for graduate_kind.id
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_kind.kind
     *
     * @return the value of graduate_kind.kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_kind.kind
     *
     * @param kind the value for graduate_kind.kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }
}