package edu.graduate.bean;

public class Npd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_npd.id
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_npd.nutrition_id
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    private Long nutritionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_npd.pregnantDescription_id
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    private Integer pregnantdescriptionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_npd.id
     *
     * @return the value of graduate_npd.id
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_npd.id
     *
     * @param id the value for graduate_npd.id
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_npd.nutrition_id
     *
     * @return the value of graduate_npd.nutrition_id
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    public Long getNutritionId() {
        return nutritionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_npd.nutrition_id
     *
     * @param nutritionId the value for graduate_npd.nutrition_id
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    public void setNutritionId(Long nutritionId) {
        this.nutritionId = nutritionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_npd.pregnantDescription_id
     *
     * @return the value of graduate_npd.pregnantDescription_id
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    public Integer getPregnantdescriptionId() {
        return pregnantdescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_npd.pregnantDescription_id
     *
     * @param pregnantdescriptionId the value for graduate_npd.pregnantDescription_id
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    public void setPregnantdescriptionId(Integer pregnantdescriptionId) {
        this.pregnantdescriptionId = pregnantdescriptionId;
    }
}