package edu.graduate.bean;

public class NutritionFruit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_nutritionfruit.id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_nutritionfruit.nutrition_id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    private Long nutritionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_nutritionfruit.fruit_id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    private Long fruitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_nutritionfruit.id
     *
     * @return the value of graduate_nutritionfruit.id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_nutritionfruit.id
     *
     * @param id the value for graduate_nutritionfruit.id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_nutritionfruit.nutrition_id
     *
     * @return the value of graduate_nutritionfruit.nutrition_id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public Long getNutritionId() {
        return nutritionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_nutritionfruit.nutrition_id
     *
     * @param nutritionId the value for graduate_nutritionfruit.nutrition_id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public void setNutritionId(Long nutritionId) {
        this.nutritionId = nutritionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_nutritionfruit.fruit_id
     *
     * @return the value of graduate_nutritionfruit.fruit_id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public Long getFruitId() {
        return fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_nutritionfruit.fruit_id
     *
     * @param fruitId the value for graduate_nutritionfruit.fruit_id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public void setFruitId(Long fruitId) {
        this.fruitId = fruitId;
    }
}