package edu.graduate.bean;

public class NutritionFruit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_nutritionfruit.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_nutritionfruit.nutrition_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer nutritionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_nutritionfruit.fruit_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer fruitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_nutritionfruit.id
     *
     * @return the value of graduate_nutritionfruit.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_nutritionfruit.id
     *
     * @param id the value for graduate_nutritionfruit.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_nutritionfruit.nutrition_id
     *
     * @return the value of graduate_nutritionfruit.nutrition_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getNutritionId() {
        return nutritionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_nutritionfruit.nutrition_id
     *
     * @param nutritionId the value for graduate_nutritionfruit.nutrition_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setNutritionId(Integer nutritionId) {
        this.nutritionId = nutritionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_nutritionfruit.fruit_id
     *
     * @return the value of graduate_nutritionfruit.fruit_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getFruitId() {
        return fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_nutritionfruit.fruit_id
     *
     * @param fruitId the value for graduate_nutritionfruit.fruit_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setFruitId(Integer fruitId) {
        this.fruitId = fruitId;
    }
}