package edu.graduate.bean;

public class PregnantWeek {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantweek.id
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantweek.pictrue
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    private String pictrue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantweek.week
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    private Integer week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantweek.yqts
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    private String yqts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantweek.bbfy
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    private String bbfy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantweek.yyts
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    private String yyts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantweek.bmxz
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    private String bmxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantweek.mmbh
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    private String mmbh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantweek.id
     *
     * @return the value of graduate_pregnantweek.id
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantweek.id
     *
     * @param id the value for graduate_pregnantweek.id
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantweek.pictrue
     *
     * @return the value of graduate_pregnantweek.pictrue
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public String getPictrue() {
        return pictrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantweek.pictrue
     *
     * @param pictrue the value for graduate_pregnantweek.pictrue
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setPictrue(String pictrue) {
        this.pictrue = pictrue == null ? null : pictrue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantweek.week
     *
     * @return the value of graduate_pregnantweek.week
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantweek.week
     *
     * @param week the value for graduate_pregnantweek.week
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantweek.yqts
     *
     * @return the value of graduate_pregnantweek.yqts
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public String getYqts() {
        return yqts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantweek.yqts
     *
     * @param yqts the value for graduate_pregnantweek.yqts
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setYqts(String yqts) {
        this.yqts = yqts == null ? null : yqts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantweek.bbfy
     *
     * @return the value of graduate_pregnantweek.bbfy
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public String getBbfy() {
        return bbfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantweek.bbfy
     *
     * @param bbfy the value for graduate_pregnantweek.bbfy
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setBbfy(String bbfy) {
        this.bbfy = bbfy == null ? null : bbfy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantweek.yyts
     *
     * @return the value of graduate_pregnantweek.yyts
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public String getYyts() {
        return yyts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantweek.yyts
     *
     * @param yyts the value for graduate_pregnantweek.yyts
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setYyts(String yyts) {
        this.yyts = yyts == null ? null : yyts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantweek.bmxz
     *
     * @return the value of graduate_pregnantweek.bmxz
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public String getBmxz() {
        return bmxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantweek.bmxz
     *
     * @param bmxz the value for graduate_pregnantweek.bmxz
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setBmxz(String bmxz) {
        this.bmxz = bmxz == null ? null : bmxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantweek.mmbh
     *
     * @return the value of graduate_pregnantweek.mmbh
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public String getMmbh() {
        return mmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantweek.mmbh
     *
     * @param mmbh the value for graduate_pregnantweek.mmbh
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setMmbh(String mmbh) {
        this.mmbh = mmbh == null ? null : mmbh.trim();
    }
}