package edu.graduate.bean;

public class preganInfoFruit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_preganinfofruit.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_preganinfofruit.preganInfo_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer preganinfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_preganinfofruit.fruit_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer fruitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_preganinfofruit.id
     *
     * @return the value of graduate_preganinfofruit.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_preganinfofruit.id
     *
     * @param id the value for graduate_preganinfofruit.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_preganinfofruit.preganInfo_id
     *
     * @return the value of graduate_preganinfofruit.preganInfo_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getPreganinfoId() {
        return preganinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_preganinfofruit.preganInfo_id
     *
     * @param preganinfoId the value for graduate_preganinfofruit.preganInfo_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setPreganinfoId(Integer preganinfoId) {
        this.preganinfoId = preganinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_preganinfofruit.fruit_id
     *
     * @return the value of graduate_preganinfofruit.fruit_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getFruitId() {
        return fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_preganinfofruit.fruit_id
     *
     * @param fruitId the value for graduate_preganinfofruit.fruit_id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setFruitId(Integer fruitId) {
        this.fruitId = fruitId;
    }
}