package edu.graduate.bean;

public class PreganInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_preganinfo.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_preganinfo.name
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_preganinfo.pregantweek
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    private Integer pregantweek;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_preganinfo.id
     *
     * @return the value of graduate_preganinfo.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_preganinfo.id
     *
     * @param id the value for graduate_preganinfo.id
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_preganinfo.name
     *
     * @return the value of graduate_preganinfo.name
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_preganinfo.name
     *
     * @param name the value for graduate_preganinfo.name
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_preganinfo.pregantweek
     *
     * @return the value of graduate_preganinfo.pregantweek
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public Integer getPregantweek() {
        return pregantweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_preganinfo.pregantweek
     *
     * @param pregantweek the value for graduate_preganinfo.pregantweek
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    public void setPregantweek(Integer pregantweek) {
        this.pregantweek = pregantweek;
    }
}