package edu.graduate.bean;

public class PregnantInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantinfo.id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantinfo.pregnantweek
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    private Integer pregnantweek;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantinfo.id
     *
     * @return the value of graduate_pregnantinfo.id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantinfo.id
     *
     * @param id the value for graduate_pregnantinfo.id
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantinfo.pregnantweek
     *
     * @return the value of graduate_pregnantinfo.pregnantweek
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public Integer getPregnantweek() {
        return pregnantweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantinfo.pregnantweek
     *
     * @param pregnantweek the value for graduate_pregnantinfo.pregnantweek
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    public void setPregnantweek(Integer pregnantweek) {
        this.pregnantweek = pregnantweek;
    }
}