package edu.graduate.bean;

import java.util.ArrayList;
import java.util.List;

public class PregnantWeekExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public PregnantWeekExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPictrueIsNull() {
            addCriterion("pictrue is null");
            return (Criteria) this;
        }

        public Criteria andPictrueIsNotNull() {
            addCriterion("pictrue is not null");
            return (Criteria) this;
        }

        public Criteria andPictrueEqualTo(String value) {
            addCriterion("pictrue =", value, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueNotEqualTo(String value) {
            addCriterion("pictrue <>", value, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueGreaterThan(String value) {
            addCriterion("pictrue >", value, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueGreaterThanOrEqualTo(String value) {
            addCriterion("pictrue >=", value, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueLessThan(String value) {
            addCriterion("pictrue <", value, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueLessThanOrEqualTo(String value) {
            addCriterion("pictrue <=", value, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueLike(String value) {
            addCriterion("pictrue like", value, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueNotLike(String value) {
            addCriterion("pictrue not like", value, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueIn(List<String> values) {
            addCriterion("pictrue in", values, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueNotIn(List<String> values) {
            addCriterion("pictrue not in", values, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueBetween(String value1, String value2) {
            addCriterion("pictrue between", value1, value2, "pictrue");
            return (Criteria) this;
        }

        public Criteria andPictrueNotBetween(String value1, String value2) {
            addCriterion("pictrue not between", value1, value2, "pictrue");
            return (Criteria) this;
        }

        public Criteria andWeekIsNull() {
            addCriterion("week is null");
            return (Criteria) this;
        }

        public Criteria andWeekIsNotNull() {
            addCriterion("week is not null");
            return (Criteria) this;
        }

        public Criteria andWeekEqualTo(Integer value) {
            addCriterion("week =", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotEqualTo(Integer value) {
            addCriterion("week <>", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThan(Integer value) {
            addCriterion("week >", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("week >=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThan(Integer value) {
            addCriterion("week <", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThanOrEqualTo(Integer value) {
            addCriterion("week <=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekIn(List<Integer> values) {
            addCriterion("week in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotIn(List<Integer> values) {
            addCriterion("week not in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekBetween(Integer value1, Integer value2) {
            addCriterion("week between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("week not between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andYqtsIsNull() {
            addCriterion("yqts is null");
            return (Criteria) this;
        }

        public Criteria andYqtsIsNotNull() {
            addCriterion("yqts is not null");
            return (Criteria) this;
        }

        public Criteria andYqtsEqualTo(String value) {
            addCriterion("yqts =", value, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsNotEqualTo(String value) {
            addCriterion("yqts <>", value, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsGreaterThan(String value) {
            addCriterion("yqts >", value, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsGreaterThanOrEqualTo(String value) {
            addCriterion("yqts >=", value, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsLessThan(String value) {
            addCriterion("yqts <", value, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsLessThanOrEqualTo(String value) {
            addCriterion("yqts <=", value, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsLike(String value) {
            addCriterion("yqts like", value, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsNotLike(String value) {
            addCriterion("yqts not like", value, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsIn(List<String> values) {
            addCriterion("yqts in", values, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsNotIn(List<String> values) {
            addCriterion("yqts not in", values, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsBetween(String value1, String value2) {
            addCriterion("yqts between", value1, value2, "yqts");
            return (Criteria) this;
        }

        public Criteria andYqtsNotBetween(String value1, String value2) {
            addCriterion("yqts not between", value1, value2, "yqts");
            return (Criteria) this;
        }

        public Criteria andBbfyIsNull() {
            addCriterion("bbfy is null");
            return (Criteria) this;
        }

        public Criteria andBbfyIsNotNull() {
            addCriterion("bbfy is not null");
            return (Criteria) this;
        }

        public Criteria andBbfyEqualTo(String value) {
            addCriterion("bbfy =", value, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyNotEqualTo(String value) {
            addCriterion("bbfy <>", value, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyGreaterThan(String value) {
            addCriterion("bbfy >", value, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyGreaterThanOrEqualTo(String value) {
            addCriterion("bbfy >=", value, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyLessThan(String value) {
            addCriterion("bbfy <", value, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyLessThanOrEqualTo(String value) {
            addCriterion("bbfy <=", value, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyLike(String value) {
            addCriterion("bbfy like", value, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyNotLike(String value) {
            addCriterion("bbfy not like", value, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyIn(List<String> values) {
            addCriterion("bbfy in", values, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyNotIn(List<String> values) {
            addCriterion("bbfy not in", values, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyBetween(String value1, String value2) {
            addCriterion("bbfy between", value1, value2, "bbfy");
            return (Criteria) this;
        }

        public Criteria andBbfyNotBetween(String value1, String value2) {
            addCriterion("bbfy not between", value1, value2, "bbfy");
            return (Criteria) this;
        }

        public Criteria andYytsIsNull() {
            addCriterion("yyts is null");
            return (Criteria) this;
        }

        public Criteria andYytsIsNotNull() {
            addCriterion("yyts is not null");
            return (Criteria) this;
        }

        public Criteria andYytsEqualTo(String value) {
            addCriterion("yyts =", value, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsNotEqualTo(String value) {
            addCriterion("yyts <>", value, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsGreaterThan(String value) {
            addCriterion("yyts >", value, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsGreaterThanOrEqualTo(String value) {
            addCriterion("yyts >=", value, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsLessThan(String value) {
            addCriterion("yyts <", value, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsLessThanOrEqualTo(String value) {
            addCriterion("yyts <=", value, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsLike(String value) {
            addCriterion("yyts like", value, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsNotLike(String value) {
            addCriterion("yyts not like", value, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsIn(List<String> values) {
            addCriterion("yyts in", values, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsNotIn(List<String> values) {
            addCriterion("yyts not in", values, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsBetween(String value1, String value2) {
            addCriterion("yyts between", value1, value2, "yyts");
            return (Criteria) this;
        }

        public Criteria andYytsNotBetween(String value1, String value2) {
            addCriterion("yyts not between", value1, value2, "yyts");
            return (Criteria) this;
        }

        public Criteria andBmxzIsNull() {
            addCriterion("bmxz is null");
            return (Criteria) this;
        }

        public Criteria andBmxzIsNotNull() {
            addCriterion("bmxz is not null");
            return (Criteria) this;
        }

        public Criteria andBmxzEqualTo(String value) {
            addCriterion("bmxz =", value, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzNotEqualTo(String value) {
            addCriterion("bmxz <>", value, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzGreaterThan(String value) {
            addCriterion("bmxz >", value, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzGreaterThanOrEqualTo(String value) {
            addCriterion("bmxz >=", value, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzLessThan(String value) {
            addCriterion("bmxz <", value, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzLessThanOrEqualTo(String value) {
            addCriterion("bmxz <=", value, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzLike(String value) {
            addCriterion("bmxz like", value, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzNotLike(String value) {
            addCriterion("bmxz not like", value, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzIn(List<String> values) {
            addCriterion("bmxz in", values, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzNotIn(List<String> values) {
            addCriterion("bmxz not in", values, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzBetween(String value1, String value2) {
            addCriterion("bmxz between", value1, value2, "bmxz");
            return (Criteria) this;
        }

        public Criteria andBmxzNotBetween(String value1, String value2) {
            addCriterion("bmxz not between", value1, value2, "bmxz");
            return (Criteria) this;
        }

        public Criteria andMmbhIsNull() {
            addCriterion("mmbh is null");
            return (Criteria) this;
        }

        public Criteria andMmbhIsNotNull() {
            addCriterion("mmbh is not null");
            return (Criteria) this;
        }

        public Criteria andMmbhEqualTo(String value) {
            addCriterion("mmbh =", value, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhNotEqualTo(String value) {
            addCriterion("mmbh <>", value, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhGreaterThan(String value) {
            addCriterion("mmbh >", value, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhGreaterThanOrEqualTo(String value) {
            addCriterion("mmbh >=", value, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhLessThan(String value) {
            addCriterion("mmbh <", value, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhLessThanOrEqualTo(String value) {
            addCriterion("mmbh <=", value, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhLike(String value) {
            addCriterion("mmbh like", value, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhNotLike(String value) {
            addCriterion("mmbh not like", value, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhIn(List<String> values) {
            addCriterion("mmbh in", values, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhNotIn(List<String> values) {
            addCriterion("mmbh not in", values, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhBetween(String value1, String value2) {
            addCriterion("mmbh between", value1, value2, "mmbh");
            return (Criteria) this;
        }

        public Criteria andMmbhNotBetween(String value1, String value2) {
            addCriterion("mmbh not between", value1, value2, "mmbh");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated do_not_delete_during_merge Sun May 19 09:06:19 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}