package edu.graduate.bean;

public class PreganInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_preganinfo.id
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_preganinfo.pregantweek
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    private Integer pregantweek;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_preganinfo.id
     *
     * @return the value of graduate_preganinfo.id
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_preganinfo.id
     *
     * @param id the value for graduate_preganinfo.id
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_preganinfo.pregantweek
     *
     * @return the value of graduate_preganinfo.pregantweek
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public Integer getPregantweek() {
        return pregantweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_preganinfo.pregantweek
     *
     * @param pregantweek the value for graduate_preganinfo.pregantweek
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    public void setPregantweek(Integer pregantweek) {
        this.pregantweek = pregantweek;
    }
}