package edu.graduate.bean;

public class PregnantDescription {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantdescription.id
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantdescription.time
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantdescription.effect
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    private String effect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_pregnantdescription.description
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantdescription.id
     *
     * @return the value of graduate_pregnantdescription.id
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantdescription.id
     *
     * @param id the value for graduate_pregnantdescription.id
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantdescription.time
     *
     * @return the value of graduate_pregnantdescription.time
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantdescription.time
     *
     * @param time the value for graduate_pregnantdescription.time
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantdescription.effect
     *
     * @return the value of graduate_pregnantdescription.effect
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    public String getEffect() {
        return effect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantdescription.effect
     *
     * @param effect the value for graduate_pregnantdescription.effect
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    public void setEffect(String effect) {
        this.effect = effect == null ? null : effect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_pregnantdescription.description
     *
     * @return the value of graduate_pregnantdescription.description
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_pregnantdescription.description
     *
     * @param description the value for graduate_pregnantdescription.description
     *
     * @mbg.generated Sun May 19 23:00:42 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	@Override
	public String toString() {
		return "PregnantDescription [id=" + id + ", time=" + time + ", effect=" + effect + ", description="
				+ description + "]";
	}
    
    
}