package edu.graduate.bean;

import java.util.Date;

public class Professor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_professor.id
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_professor.name
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_professor.datetime
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    private Date datetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_professor.topicKind_id
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    private Integer topickindId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_professor.cotent
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    private String cotent;
    
    private TopicKind kind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_professor.id
     *
     * @return the value of graduate_professor.id
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_professor.id
     *
     * @param id the value for graduate_professor.id
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_professor.name
     *
     * @return the value of graduate_professor.name
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_professor.name
     *
     * @param name the value for graduate_professor.name
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_professor.datetime
     *
     * @return the value of graduate_professor.datetime
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_professor.datetime
     *
     * @param datetime the value for graduate_professor.datetime
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_professor.topicKind_id
     *
     * @return the value of graduate_professor.topicKind_id
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public Integer getTopickindId() {
        return topickindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_professor.topicKind_id
     *
     * @param topickindId the value for graduate_professor.topicKind_id
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public void setTopickindId(Integer topickindId) {
        this.topickindId = topickindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_professor.cotent
     *
     * @return the value of graduate_professor.cotent
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public String getCotent() {
        return cotent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_professor.cotent
     *
     * @param cotent the value for graduate_professor.cotent
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public void setCotent(String cotent) {
        this.cotent = cotent == null ? null : cotent.trim();
    }

	

	public TopicKind getKind() {
		return kind;
	}

	public void setKind(TopicKind kind) {
		this.kind = kind;
	}

	@Override
	public String toString() {
		return "Professor [id=" + id + ", name=" + name + ", datetime=" + datetime + ", topickindId=" + topickindId
				+ ", cotent=" + cotent + ", kind=" + kind + "]";
	}
	
}