package edu.graduate.bean;

public class Reason {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_reason.id
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_reason.pregnantEat
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    private String pregnanteat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_reason.momEat
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    private String momeat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_reason.babyEat
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    private String babyeat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_reason.fruit_id
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    private Long fruitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_reason.id
     *
     * @return the value of graduate_reason.id
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_reason.id
     *
     * @param id the value for graduate_reason.id
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_reason.pregnantEat
     *
     * @return the value of graduate_reason.pregnantEat
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public String getPregnanteat() {
        return pregnanteat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_reason.pregnantEat
     *
     * @param pregnanteat the value for graduate_reason.pregnantEat
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public void setPregnanteat(String pregnanteat) {
        this.pregnanteat = pregnanteat == null ? null : pregnanteat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_reason.momEat
     *
     * @return the value of graduate_reason.momEat
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public String getMomeat() {
        return momeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_reason.momEat
     *
     * @param momeat the value for graduate_reason.momEat
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public void setMomeat(String momeat) {
        this.momeat = momeat == null ? null : momeat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_reason.babyEat
     *
     * @return the value of graduate_reason.babyEat
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public String getBabyeat() {
        return babyeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_reason.babyEat
     *
     * @param babyeat the value for graduate_reason.babyEat
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public void setBabyeat(String babyeat) {
        this.babyeat = babyeat == null ? null : babyeat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_reason.fruit_id
     *
     * @return the value of graduate_reason.fruit_id
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public Long getFruitId() {
        return fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_reason.fruit_id
     *
     * @param fruitId the value for graduate_reason.fruit_id
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    public void setFruitId(Long fruitId) {
        this.fruitId = fruitId;
    }
}