package edu.graduate.bean;

public class TopicKind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_topickind.id
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_topickind.kind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    private String kind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_topickind.id
     *
     * @return the value of graduate_topickind.id
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_topickind.id
     *
     * @param id the value for graduate_topickind.id
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_topickind.kind
     *
     * @return the value of graduate_topickind.kind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_topickind.kind
     *
     * @param kind the value for graduate_topickind.kind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }
}