package edu.graduate.bean;

public class Yqbd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_yqbd.id
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_yqbd.showPicture
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    private String showpicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_yqbd.name
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_yqbd.picture
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_yqbd.discription
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    private String discription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_yqbd.id
     *
     * @return the value of graduate_yqbd.id
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_yqbd.id
     *
     * @param id the value for graduate_yqbd.id
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_yqbd.showPicture
     *
     * @return the value of graduate_yqbd.showPicture
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public String getShowpicture() {
        return showpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_yqbd.showPicture
     *
     * @param showpicture the value for graduate_yqbd.showPicture
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public void setShowpicture(String showpicture) {
        this.showpicture = showpicture == null ? null : showpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_yqbd.name
     *
     * @return the value of graduate_yqbd.name
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_yqbd.name
     *
     * @param name the value for graduate_yqbd.name
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_yqbd.picture
     *
     * @return the value of graduate_yqbd.picture
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_yqbd.picture
     *
     * @param picture the value for graduate_yqbd.picture
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_yqbd.discription
     *
     * @return the value of graduate_yqbd.discription
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_yqbd.discription
     *
     * @param discription the value for graduate_yqbd.discription
     *
     * @mbg.generated Sat May 18 22:51:34 CST 2019
     */
    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }

	@Override
	public String toString() {
		return "Yqbd [id=" + id + ", showpicture=" + showpicture + ", name=" + name + ", picture=" + picture
				+ ", discription=" + discription + "]";
	}
    
}