package edu.graduate.dao;

import edu.graduate.bean.Article;
import edu.graduate.bean.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    long countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int deleteByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    List<Article> selectByExampleWithBLOBs(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    Article selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByPrimaryKey(Article record);
}