package edu.graduate.dao;

import edu.graduate.bean.Article;
import edu.graduate.bean.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    long countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int deleteByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    List<Article> selectByExampleWithBLOBs(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_article
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);
}