package edu.graduate.dao;

import edu.graduate.bean.Comment;
import edu.graduate.bean.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    long countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    List<Comment> selectByExampleWithBLOBs(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_comment
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByPrimaryKey(Comment record);
}