package edu.graduate.dao;

import edu.graduate.bean.Fruit;
import edu.graduate.bean.FruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    long countByExample(FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int deleteByExample(FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int insert(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int insertSelective(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    List<Fruit> selectByExampleWithBLOBs(FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    List<Fruit> selectByExample(FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    Fruit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Fruit record, @Param("example") FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Fruit record, @Param("example") FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByExample(@Param("record") Fruit record, @Param("example") FruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByPrimaryKeySelective(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_fruit
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByPrimaryKey(Fruit record);
}