package edu.graduate.dao;

import edu.graduate.bean.ImgIndex;
import edu.graduate.bean.ImgIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    long countByExample(ImgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int deleteByExample(ImgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int insert(ImgIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int insertSelective(ImgIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    List<ImgIndex> selectByExample(ImgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    ImgIndex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") ImgIndex record, @Param("example") ImgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int updateByExample(@Param("record") ImgIndex record, @Param("example") ImgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int updateByPrimaryKeySelective(ImgIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgindex
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int updateByPrimaryKey(ImgIndex record);
}