package edu.graduate.dao;

import edu.graduate.bean.ImgPregnant;
import edu.graduate.bean.ImgPregnantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgPregnantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    long countByExample(ImgPregnantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    int deleteByExample(ImgPregnantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    int insert(ImgPregnant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    int insertSelective(ImgPregnant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    List<ImgPregnant> selectByExample(ImgPregnantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    ImgPregnant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") ImgPregnant record, @Param("example") ImgPregnantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    int updateByExample(@Param("record") ImgPregnant record, @Param("example") ImgPregnantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    int updateByPrimaryKeySelective(ImgPregnant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_imgpregnant
     *
     * @mbg.generated Sat May 11 22:37:48 CST 2019
     */
    int updateByPrimaryKey(ImgPregnant record);
}