package edu.graduate.dao;

import edu.graduate.bean.Kind;
import edu.graduate.bean.KindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    long countByExample(KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int deleteByExample(KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int insert(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int insertSelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    List<Kind> selectByExample(KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    Kind selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Kind record, @Param("example") KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int updateByExample(@Param("record") Kind record, @Param("example") KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int updateByPrimaryKeySelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_kind
     *
     * @mbg.generated Fri May 03 14:26:15 CST 2019
     */
    int updateByPrimaryKey(Kind record);
}