package edu.graduate.dao;

import edu.graduate.bean.LoginRegister;
import edu.graduate.bean.LoginRegisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    long countByExample(LoginRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int deleteByExample(LoginRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int insert(LoginRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int insertSelective(LoginRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    List<LoginRegister> selectByExample(LoginRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    LoginRegister selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") LoginRegister record, @Param("example") LoginRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByExample(@Param("record") LoginRegister record, @Param("example") LoginRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByPrimaryKeySelective(LoginRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_loginregister
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByPrimaryKey(LoginRegister record);
}