package edu.graduate.dao;

import edu.graduate.bean.Manager;
import edu.graduate.bean.ManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    long countByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    int deleteByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    List<Manager> selectByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    Manager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Manager record, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    int updateByExample(@Param("record") Manager record, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_manager
     *
     * @mbg.generated Tue May 21 15:54:08 CST 2019
     */
    int updateByPrimaryKey(Manager record);
    
    Manager findManagerByName(String name);
}