package edu.graduate.dao;

import edu.graduate.bean.MeituShow;
import edu.graduate.bean.MeituShowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeituShowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    long countByExample(MeituShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    int deleteByExample(MeituShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    int insert(MeituShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    int insertSelective(MeituShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    List<MeituShow> selectByExample(MeituShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    MeituShow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") MeituShow record, @Param("example") MeituShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    int updateByExample(@Param("record") MeituShow record, @Param("example") MeituShowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    int updateByPrimaryKeySelective(MeituShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_meitushow
     *
     * @mbg.generated Sun May 19 12:03:49 CST 2019
     */
    int updateByPrimaryKey(MeituShow record);
    
    MeituShow selectByimgpath(String imgpath);
}