package edu.graduate.dao;

import edu.graduate.bean.Npd;
import edu.graduate.bean.NpdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NpdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    long countByExample(NpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    int deleteByExample(NpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    int insert(Npd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    int insertSelective(Npd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    List<Npd> selectByExample(NpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    Npd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Npd record, @Param("example") NpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    int updateByExample(@Param("record") Npd record, @Param("example") NpdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    int updateByPrimaryKeySelective(Npd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_npd
     *
     * @mbg.generated Sun May 19 22:37:24 CST 2019
     */
    int updateByPrimaryKey(Npd record);
}