package edu.graduate.dao;

import edu.graduate.bean.Nutrition;
import edu.graduate.bean.NutritionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NutritionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    long countByExample(NutritionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int deleteByExample(NutritionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int insert(Nutrition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int insertSelective(Nutrition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    List<Nutrition> selectByExampleWithBLOBs(NutritionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    List<Nutrition> selectByExample(NutritionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    Nutrition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Nutrition record, @Param("example") NutritionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Nutrition record, @Param("example") NutritionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int updateByExample(@Param("record") Nutrition record, @Param("example") NutritionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int updateByPrimaryKeySelective(Nutrition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Nutrition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutrition
     *
     * @mbg.generated Tue Apr 16 19:10:23 CST 2019
     */
    int updateByPrimaryKey(Nutrition record);
}