package edu.graduate.dao;

import edu.graduate.bean.NutritionFruit;
import edu.graduate.bean.NutritionFruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NutritionFruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    long countByExample(NutritionFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int deleteByExample(NutritionFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int insert(NutritionFruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int insertSelective(NutritionFruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    List<NutritionFruit> selectByExample(NutritionFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    NutritionFruit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") NutritionFruit record, @Param("example") NutritionFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByExample(@Param("record") NutritionFruit record, @Param("example") NutritionFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByPrimaryKeySelective(NutritionFruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_nutritionfruit
     *
     * @mbg.generated Thu Apr 18 09:50:43 CST 2019
     */
    int updateByPrimaryKey(NutritionFruit record);
}