package edu.graduate.dao;

import edu.graduate.bean.PregnantWeek;
import edu.graduate.bean.PregnantWeekExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PregnantWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    long countByExample(PregnantWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    int deleteByExample(PregnantWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    int insert(PregnantWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    int insertSelective(PregnantWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    List<PregnantWeek> selectByExample(PregnantWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    PregnantWeek selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") PregnantWeek record, @Param("example") PregnantWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    int updateByExample(@Param("record") PregnantWeek record, @Param("example") PregnantWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    int updateByPrimaryKeySelective(PregnantWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantweek
     *
     * @mbg.generated Sun May 19 09:06:19 CST 2019
     */
    int updateByPrimaryKey(PregnantWeek record);
    
    PregnantWeek selectByWeek(Integer week);
}