package edu.graduate.dao;

import edu.graduate.bean.PreganInfo;
import edu.graduate.bean.PreganInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreganInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    long countByExample(PreganInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int deleteByExample(PreganInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int insert(PreganInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int insertSelective(PreganInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    List<PreganInfo> selectByExample(PreganInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    PreganInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") PreganInfo record, @Param("example") PreganInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByExample(@Param("record") PreganInfo record, @Param("example") PreganInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByPrimaryKeySelective(PreganInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfo
     *
     * @mbg.generated Sat Apr 13 15:28:16 CST 2019
     */
    int updateByPrimaryKey(PreganInfo record);
}