package edu.graduate.dao;

import edu.graduate.bean.PregnantInfo;
import edu.graduate.bean.PregnantInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PregnantInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    long countByExample(PregnantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    int deleteByExample(PregnantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    int insert(PregnantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    int insertSelective(PregnantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    List<PregnantInfo> selectByExample(PregnantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    PregnantInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") PregnantInfo record, @Param("example") PregnantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    int updateByExample(@Param("record") PregnantInfo record, @Param("example") PregnantInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    int updateByPrimaryKeySelective(PregnantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantinfo
     *
     * @mbg.generated Sat Apr 13 22:33:56 CST 2019
     */
    int updateByPrimaryKey(PregnantInfo record);
}