package edu.graduate.dao;

import edu.graduate.bean.PregnantAnalysis;
import edu.graduate.bean.PregnantAnalysisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PregnantAnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    long countByExample(PregnantAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int deleteByExample(PregnantAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int insert(PregnantAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int insertSelective(PregnantAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    List<PregnantAnalysis> selectByExampleWithBLOBs(PregnantAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    List<PregnantAnalysis> selectByExample(PregnantAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    PregnantAnalysis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") PregnantAnalysis record, @Param("example") PregnantAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") PregnantAnalysis record, @Param("example") PregnantAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int updateByExample(@Param("record") PregnantAnalysis record, @Param("example") PregnantAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int updateByPrimaryKeySelective(PregnantAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(PregnantAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_pregnantanalysis
     *
     * @mbg.generated Sun May 19 10:30:56 CST 2019
     */
    int updateByPrimaryKey(PregnantAnalysis record);
    
    List<PregnantAnalysis> selectPregnantAnalysisByKindId(Long id);
    
    PregnantAnalysis selectByName(String name);
    
    PregnantAnalysis selectKindBykindId(Long id);
}