package edu.graduate.dao;

import edu.graduate.bean.preganInfoFruit;
import edu.graduate.bean.preganInfoFruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface preganInfoFruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    long countByExample(preganInfoFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int deleteByExample(preganInfoFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int insert(preganInfoFruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int insertSelective(preganInfoFruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    List<preganInfoFruit> selectByExample(preganInfoFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    preganInfoFruit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") preganInfoFruit record, @Param("example") preganInfoFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByExample(@Param("record") preganInfoFruit record, @Param("example") preganInfoFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByPrimaryKeySelective(preganInfoFruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_preganinfofruit
     *
     * @mbg.generated Fri Apr 12 20:03:16 CST 2019
     */
    int updateByPrimaryKey(preganInfoFruit record);
}