package edu.graduate.dao;

import edu.graduate.bean.Reason;
import edu.graduate.bean.ReasonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    long countByExample(ReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    int deleteByExample(ReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    int insert(Reason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    int insertSelective(Reason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    List<Reason> selectByExample(ReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    Reason selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") Reason record, @Param("example") ReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    int updateByExample(@Param("record") Reason record, @Param("example") ReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    int updateByPrimaryKeySelective(Reason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_reason
     *
     * @mbg.generated Sat May 18 10:47:29 CST 2019
     */
    int updateByPrimaryKey(Reason record);
}