package edu.graduate.dao;

import edu.graduate.bean.TopicKind;
import edu.graduate.bean.TopicKindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicKindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    long countByExample(TopicKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    int deleteByExample(TopicKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    int insert(TopicKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    int insertSelective(TopicKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    List<TopicKind> selectByExample(TopicKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    TopicKind selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") TopicKind record, @Param("example") TopicKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    int updateByExample(@Param("record") TopicKind record, @Param("example") TopicKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    int updateByPrimaryKeySelective(TopicKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduate_topickind
     *
     * @mbg.generated Tue May 21 10:16:40 CST 2019
     */
    int updateByPrimaryKey(TopicKind record);
    
    List<TopicKind> findAll();
}